# Generated by Django 5.2.17 on 2026-08-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0006_spot_status_outbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='placed_photo',
            field=models.ImageField(blank=True, null=True, upload_to='placed/'),
        ),
    ]
