# Generated by Django 5.2.17 on 2026-08-29 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0007_spot_placed_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Giveaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.PositiveIntegerField(unique=True)),
                ('tweet_id', models.CharField(blank=True, default='', max_length=32)),
                ('tweet_handle', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='giveaway', to='spots.spot')),
            ],
            options={
                'ordering': ['seat'],
            },
        ),
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='spots.spot')),
            ],
            options={
                'indexes': [models.Index(fields=['spot', '-created_at'], name='spots_click_spot_id_4c28f5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ip_hash', ''), _negated=True), fields=('spot', 'ip_hash'), name='one_click_per_ip_per_spot')],
            },
        ),
    ]
