# Generated by Django 5.2.17 on 2026-08-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0008_spot_clicks_count_giveaway_click'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='giveaway',
            constraint=models.UniqueConstraint(condition=models.Q(('tweet_id', ''), _negated=True), fields=('tweet_id',), name='one_seat_per_post'),
        ),
    ]
